#!/usr/bin/env python3
"""(Re)build the tilelang VAD assets embedded in otograph.

Produces, relative to the otograph root:
  assets/k_<name>.cubin   (7 compiled tilelang kernels)
  assets/w_*.bin          (14 weight blobs extracted from the ONNX)
  src/vad_assets.rs       (include_bytes! consts + per-kernel KSpec with slots
                           in the cubin's ACTUAL arg order, read from each
                           kernel's metadata.json — reorder-proof)

The 7 kernels are authored in the sibling tilelang-poc/vad/ project
(kernels2.py); this script imports them so there is one source of truth. The
ONNX (model/silero_vad_16k.onnx) is read only for its weights.

Output is committed; rerun this only to regenerate after changing the kernels.
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ONNX = os.path.join(ROOT, "model", "silero_vad_16k.onnx")
ASSETS = os.path.join(ROOT, "assets")
# The tilelang kernel source lives in the sibling exploratory project.
TLVAD = os.environ.get("OTOGRAPH_TLVAD", os.path.join(ROOT, "..", "tilelang-poc", "vad"))
TLKERNEL = os.environ.get("OTOGRAPH_TLKERN", os.path.join(ROOT, "..", "tilelang-poc", "kernel"))

sys.path.insert(0, TLVAD)
sys.path.insert(0, TLKERNEL)
import kernels2 as K2  # noqa: E402
import tlcompile  # noqa: E402
from reference import load_weights  # noqa: E402

# (spec name, prim_func) — order is the forward chain order.
SPECS = [
    ("stft2", K2.stft2),
    ("conv0_2", K2.conv0_2),
    ("conv1_2", K2.conv1_2),
    ("conv2_2", K2.conv2_2),
    ("conv3_2", K2.conv3_2),
    ("Kz", K2.Kz),
    ("Kgate", K2.Kgate),
]

# per-kernel arg-name -> Slot variant (the device buffer it binds to).
ARG_SLOT = {
    "stft2":  {"xpad": "Xpad", "basis": "Basis", "spec": "Spec"},
    "conv0_2": {"x": "Spec", "w": "Ew0", "b": "Eb0", "y": "E0"},
    "conv1_2": {"x": "E0", "w": "Ew1", "b": "Eb1", "y": "E1"},
    "conv2_2": {"x": "E1", "w": "Ew2", "b": "Eb2", "y": "E2"},
    "conv3_2": {"x": "E2", "w": "Ew3", "b": "Eb3", "y": "Feat"},
    "Kz":     {"feat": "Feat", "h": "H", "c": "C", "W": "Wl", "R": "Rl", "b": "Lb", "z": "Z"},
    "Kgate":  {"z": "Z", "h": "H", "c": "C", "fc_w": "Fcw", "fc_b": "Fcb",
               "prob": "Prob", "h_out": "H2", "c_out": "C2"},
}

# weight Slot -> (filename, numpy array) — the resident buffers uploaded at load.
def weight_blobs():
    W = load_weights(ONNX)
    return [
        ("Basis", "w_basis.bin", np.ascontiguousarray(W["stft.forward_basis_buffer"].astype(np.float32)[:, 0, :])),
        ("Ew0", "w_ew0.bin", np.ascontiguousarray(W["encoder.0.reparam_conv.weight"].astype(np.float32))),
        ("Ew1", "w_ew1.bin", np.ascontiguousarray(W["encoder.1.reparam_conv.weight"].astype(np.float32))),
        ("Ew2", "w_ew2.bin", np.ascontiguousarray(W["encoder.2.reparam_conv.weight"].astype(np.float32))),
        ("Ew3", "w_ew3.bin", np.ascontiguousarray(W["encoder.3.reparam_conv.weight"].astype(np.float32))),
        ("Eb0", "w_eb0.bin", np.ascontiguousarray(W["encoder.0.reparam_conv.bias"].astype(np.float32))),
        ("Eb1", "w_eb1.bin", np.ascontiguousarray(W["encoder.1.reparam_conv.bias"].astype(np.float32))),
        ("Eb2", "w_eb2.bin", np.ascontiguousarray(W["encoder.2.reparam_conv.bias"].astype(np.float32))),
        ("Eb3", "w_eb3.bin", np.ascontiguousarray(W["encoder.3.reparam_conv.bias"].astype(np.float32))),
        ("Wl", "w_W.bin", np.ascontiguousarray(W["onnx::LSTM_283"].astype(np.float32).reshape(512, 128))),
        ("Rl", "w_R.bin", np.ascontiguousarray(W["onnx::LSTM_284"].astype(np.float32).reshape(512, 128))),
        ("Lb", "w_lb.bin", np.ascontiguousarray(
            (W["onnx::LSTM_285"].astype(np.float32).reshape(1024)[:512]
             + W["onnx::LSTM_285"].astype(np.float32).reshape(1024)[512:]))),
        ("Fcw", "w_fcw.bin", np.ascontiguousarray(W["decoder.decoder.2.weight"].astype(np.float32).reshape(128))),
        ("Fcb", "w_fcb.bin", np.ascontiguousarray(W["decoder.decoder.2.bias"].astype(np.float32).reshape(1))),
    ]


def main():
    os.makedirs(ASSETS, exist_ok=True)
    # 1. compile 7 kernels -> cubin + metadata.json in assets/
    metas = {}
    for name, fn in SPECS:
        cubin = os.path.join(ASSETS, f"k_{name}.cubin")
        meta = os.path.join(ASSETS, f"k_{name}.json")
        tlcompile.compile_kernel(fn, cubin, meta)
        metas[name] = json.load(open(meta))
    # 2. dump weights
    blobs = weight_blobs()
    for _, fname, arr in blobs:
        assert arr.dtype == np.float32
        open(os.path.join(ASSETS, fname), "wb").write(np.ascontiguousarray(arr).tobytes())

    # 3. emit src/vad_assets.rs
    rs = ["// AUTO-GENERATED by scripts/build_vad_kernels.py — do not edit.",
          "// 7 tilelang VAD kernels (cubins) + 14 weight blobs, with per-kernel",
          "// launch specs whose `slots` follow the cubin's actual arg order.",
          "",
          "#[repr(u8)] #[derive(Clone, Copy, PartialEq, Eq)]",
          "pub enum Slot {",
          "    Xpad, Basis, Spec, E0, E1, E2, Feat, Z, Prob,",
          "    H, C, H2, C2,",
          "    Ew0, Ew1, Ew2, Ew3, Eb0, Eb1, Eb2, Eb3,",
          "    Wl, Rl, Lb, Fcw, Fcb,",
          "}",
          "",
          "pub struct KSpec {",
          "    pub cubin: &'static [u8],",
          "    pub name: &'static str,",
          "    pub grid: [u32; 3],",
          "    pub block: [u32; 3],",
          "    pub shmem: u32,",
          "    pub slots: &'static [Slot],",
          "}",
          ""]
    # cubin + weight include_bytes consts
    for name, _ in SPECS:
        rs.append(f'pub const CUBIN_{name.upper()}: &[u8] = include_bytes!("../assets/k_{name}.cubin");')
    rs.append("")
    for slot, fname, _ in blobs:
        rs.append(f'pub const W_{slot.upper()}: &[u8] = include_bytes!("../assets/{fname}");')
    rs.append("")
    rs.append("pub const WEIGHTS: &[(Slot, &[u8])] = &[")
    for slot, _, _ in blobs:
        rs.append(f"    (Slot::{slot}, W_{slot.upper()}),")
    rs.append("];")
    rs.append("")
    # KSpec per kernel
    spec_id = {"stft2": "STFT2", "conv0_2": "CONV0", "conv1_2": "CONV1",
               "conv2_2": "CONV2", "conv3_2": "CONV3", "Kz": "KZ", "Kgate": "KGATE"}
    rs.append("pub const KERNELS: &[KSpec] = &[")
    for name, _ in SPECS:
        m = metas[name]
        g = (m["grid"] + [1, 1, 1])[:3]
        b = (m["block"] + [1, 1, 1])[:3]
        shmem = int(m.get("shared_mem_bytes", 0))
        slots = ", ".join(f"Slot::{ARG_SLOT[name][a['name']]}" for a in m["args"])
        rs.append("    KSpec {")
        rs.append(f'        cubin: CUBIN_{name.upper()}, name: "{m["kernel_name"]}",')
        rs.append(f"        grid: [{g[0]}, {g[1]}, {g[2]}], block: [{b[0]}, {b[1]}, {b[2]}],")
        rs.append(f"        shmem: {shmem}, slots: &[{slots}],")
        rs.append("    },")
    rs.append("];")
    rs.append("")
    out = os.path.join(ROOT, "src", "vad_assets.rs")
    open(out, "w").write("\n".join(rs))
    print(f"wrote {len(SPECS)} cubins + {len(blobs)} weights -> {ASSETS}/")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
