#!/usr/bin/env python3
"""(Re)build the tilelang VAD assets embedded in otograph.

Produces, relative to the otograph root:
  assets/k_vad_staged.cubin   (1 compiled tilelang kernel — the staged fused
                               cooperative kernel: STFT→4 conv→LSTM→FC in one
                               cooperatively-launched kernel with shared-mem
                               weight staging + grid-sync between stages)
  assets/w_*.bin              (14 weight blobs extracted from the ONNX)
  src/vad_assets.rs           (include_bytes! consts + the KSpec with slots in
                               the cubin's ACTUAL arg order, reorder-proof)

The fused kernel is authored in the sibling tilelang-poc/vad/ project
(kernels6.py: vad_staged); this script imports it so there is one source of
truth. The ONNX (model/silero_vad_16k.onnx) is read only for its weights.

Why one fused cooperative kernel (not the 7-kernel chain): on this Jetson the
per-kernel launch/dispatch floor is ~5us and CUDA-graph replay does NOT reduce
it (measured: 7-kernel graph == 7 individual launches). The 7-kernel chain was
~45us GPU-only (35us dispatch + 10us compute) / ~70us in Rust. Fusing to one
cooperatively-launched kernel collapses the 7 dispatches into 1, and shared-mem
staging keeps the compute at ~10us, landing ~30us kernel / ~35us Rust forward.

Output is committed; rerun this only to regenerate after changing the kernel.
"""
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ONNX = os.path.join(ROOT, "model", "silero_vad_16k.onnx")
ASSETS = os.path.join(ROOT, "assets")
TLVAD = os.environ.get("OTOGRAPH_TLVAD", os.path.join(ROOT, "..", "tilelang-poc", "vad"))
TLKERNEL = os.environ.get("OTOGRAPH_TLKERN", os.path.join(ROOT, "..", "tilelang-poc", "kernel"))

sys.path.insert(0, TLVAD)
sys.path.insert(0, TLKERNEL)
import kernels6 as K6  # noqa: E402
import tlcompile  # noqa: E402
from reference import load_weights  # noqa: E402

# The single fused kernel.
KERNEL_NAME = "vad_staged"
KERNEL_FN = K6.vad_staged

# arg-name -> Slot variant (the device buffer it binds to). Covers all 24 args.
ARG_SLOT = {
    "xpad": "Xpad", "basis": "Basis",
    "ew0": "Ew0", "eb0": "Eb0", "ew1": "Ew1", "eb1": "Eb1",
    "ew2": "Ew2", "eb2": "Eb2", "ew3": "Ew3", "eb3": "Eb3",
    "Wl": "Wl", "Rl": "Rl", "Bl": "Lb", "fcw": "Fcw", "fcb": "Fcb",
    "spec_g": "SpecG", "e0_g": "E0G", "e1_g": "E1G", "e2_g": "E2G",
    "feat_g": "FeatG", "z_g": "ZG",
    "h": "H", "c": "C", "prob": "Prob",
}


def weight_blobs():
    W = load_weights(ONNX)
    return [
        ("Basis", "w_basis.bin", np.ascontiguousarray(W["stft.forward_basis_buffer"].astype(np.float32)[:, 0, :])),
        ("Ew0", "w_ew0.bin", np.ascontiguousarray(W["encoder.0.reparam_conv.weight"].astype(np.float32))),
        ("Ew1", "w_ew1.bin", np.ascontiguousarray(W["encoder.1.reparam_conv.weight"].astype(np.float32))),
        ("Ew2", "w_ew2.bin", np.ascontiguousarray(W["encoder.2.reparam_conv.weight"].astype(np.float32))),
        ("Ew3", "w_ew3.bin", np.ascontiguousarray(W["encoder.3.reparam_conv.weight"].astype(np.float32))),
        ("Eb0", "w_eb0.bin", np.ascontiguousarray(W["encoder.0.reparam_conv.bias"].astype(np.float32))),
        ("Eb1", "w_eb1.bin", np.ascontiguousarray(W["encoder.1.reparam_conv.bias"].astype(np.float32))),
        ("Eb2", "w_eb2.bin", np.ascontiguousarray(W["encoder.2.reparam_conv.bias"].astype(np.float32))),
        ("Eb3", "w_eb3.bin", np.ascontiguousarray(W["encoder.3.reparam_conv.bias"].astype(np.float32))),
        ("Wl", "w_W.bin", np.ascontiguousarray(W["onnx::LSTM_283"].astype(np.float32).reshape(512, 128))),
        ("Rl", "w_R.bin", np.ascontiguousarray(W["onnx::LSTM_284"].astype(np.float32).reshape(512, 128))),
        ("Lb", "w_lb.bin", np.ascontiguousarray(
            (W["onnx::LSTM_285"].astype(np.float32).reshape(1024)[:512]
             + W["onnx::LSTM_285"].astype(np.float32).reshape(1024)[512:]))),
        ("Fcw", "w_fcw.bin", np.ascontiguousarray(W["decoder.decoder.2.weight"].astype(np.float32).reshape(128))),
        ("Fcb", "w_fcb.bin", np.ascontiguousarray(W["decoder.decoder.2.bias"].astype(np.float32).reshape(1))),
    ]


def main():
    os.makedirs(ASSETS, exist_ok=True)
    # 1. compile the fused kernel -> cubin + metadata.json
    cubin = os.path.join(ASSETS, f"k_{KERNEL_NAME}.cubin")
    metapath = os.path.join(ASSETS, f"k_{KERNEL_NAME}.json")
    tlcompile.compile_kernel(KERNEL_FN, cubin, metapath)
    meta = json.load(open(metapath))
    assert meta.get("cooperative"), "vad_staged did not mark cooperative (no sync_grid?)"
    # 2. dump weights
    blobs = weight_blobs()
    for _, fname, arr in blobs:
        assert arr.dtype == np.float32
        open(os.path.join(ASSETS, fname), "wb").write(np.ascontiguousarray(arr).tobytes())

    # 3. emit src/vad_assets.rs
    rs = ["// AUTO-GENERATED by scripts/build_vad_kernels.py — do not edit.",
          "// 1 fused tilelang VAD kernel (cooperative) + 14 weight blobs. The KSpec's",
          "// `slots` follow the cubin's actual arg order (reorder-proof).",
          "",
          "#[repr(u8)] #[derive(Clone, Copy, PartialEq, Eq)]",
          "pub enum Slot {",
          "    Xpad, Basis,",
          "    Ew0, Ew1, Ew2, Ew3, Eb0, Eb1, Eb2, Eb3,",
          "    Wl, Rl, Lb, Fcw, Fcb,",
          "    SpecG, E0G, E1G, E2G, FeatG, ZG,",
          "    H, C, Prob,",
          "}",
          "",
          "pub struct KSpec {",
          "    pub cubin: &'static [u8],",
          "    pub name: &'static str,",
          "    pub grid: [u32; 3],",
          "    pub block: [u32; 3],",
          "    pub shmem: u32,",
          "    pub cooperative: bool,",
          "    pub slots: &'static [Slot],",
          "}",
          "",
          f'pub const CUBIN_VAD_STAGED: &[u8] = include_bytes!("../assets/k_{KERNEL_NAME}.cubin");',
          ""]
    for slot, fname, _ in blobs:
        rs.append(f'pub const W_{slot.upper()}: &[u8] = include_bytes!("../assets/{fname}");')
    rs.append("")
    rs.append("pub const WEIGHTS: &[(Slot, &[u8])] = &[")
    for slot, _, _ in blobs:
        rs.append(f"    (Slot::{slot}, W_{slot.upper()}),")
    rs.append("];")
    rs.append("")
    g = (meta["grid"] + [1, 1, 1])[:3]
    b = (meta["block"] + [1, 1, 1])[:3]
    shmem = int(meta.get("shared_mem_bytes", 0))
    coop = "true" if meta.get("cooperative") else "false"
    slots = ", ".join(f"Slot::{ARG_SLOT[a['name']]}" for a in meta["args"])
    rs.append("pub const KERNELS: &[KSpec] = &[")
    rs.append("    KSpec {")
    rs.append(f'        cubin: CUBIN_VAD_STAGED, name: "{meta["kernel_name"]}",')
    rs.append(f"        grid: [{g[0]}, {g[1]}, {g[2]}], block: [{b[0]}, {b[1]}, {b[2]}],")
    rs.append(f"        shmem: {shmem}, cooperative: {coop}, slots: &[{slots}],")
    rs.append("    },")
    rs.append("];")
    rs.append("")
    out = os.path.join(ROOT, "src", "vad_assets.rs")
    open(out, "w").write("\n".join(rs))
    print(f"wrote 1 cubin (cooperative grid={g[0]}) + {len(blobs)} weights -> {ASSETS}/")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
