//! Silero VAD via the tilelang-compiled kernels launched through the CUDA
//! driver (`libcuda.so`) only — no ONNX Runtime / TensorRT at runtime.
//!
//! The 7 shared-memory FP32 cubins and the model weights are embedded
//! (`vad_assets.rs`, generated by `scripts/build_vad_kernels.py`). The forward
//! mirrors the fixed-16k Silero VAD exactly:
//!
//!   input[1,576] = context[64] ++ window[512]  (16 kHz)
//!   -> right-side reflect-pad to 640
//!   -> STFT (basis 258x256, stride 128) -> 4 frames -> magnitude [129,4]
//!   -> 4 Conv1d (stride 1/2/2/1) + relu -> feat[128]
//!   -> LSTM cell (iofc) + relu + FC + sigmoid -> prob, new state [h;c]
//!
//! The state machine below (`speech_timestamps`) is a line-by-line port of the
//! official `silero_vad` `get_speech_timestamps`; only the per-window `forward`
//! is custom (the tilelang kernel chain).

use anyhow::{anyhow, Context, Result};
use libloading::Library;
use std::os::raw::{c_char, c_int, c_uint, c_void};

use crate::vad_assets::{KERNELS, WEIGHTS, KSpec, Slot};

const WINDOW: usize = 512; // 16 kHz -> 32 ms hop
const CONTEXT: usize = 64;
const INPUT_LEN: usize = WINDOW + CONTEXT; // 576
const XPAD_LEN: usize = 640; // INPUT_LEN + right reflect-pad 64

// ---------------- CUDA driver FFI ----------------

type Curesult = c_int;
type Cudevice = c_int;
type Cucontext = *mut c_void;
type Culibrary = *mut c_void;
type Cukernel = *mut c_void;
type Cufunction = *mut c_void;
type Cudeviceptr = u64;
type Custream = *mut c_void;
const CUDA_SUCCESS: Curesult = 0;

#[repr(C)]
#[derive(Default)]
struct CuLaunchConfig {
    grid_dim_x: c_uint, grid_dim_y: c_uint, grid_dim_z: c_uint,
    block_dim_x: c_uint, block_dim_y: c_uint, block_dim_z: c_uint,
    shared_mem_bytes: c_uint,
    h_stream: Custream,
    attrs: *mut c_void,
    num_attrs: c_uint,
}

fn cuerr(r: Curesult, what: &str) -> Result<()> {
    if r == CUDA_SUCCESS { Ok(()) } else { Err(anyhow!("CUDA driver error {r} in {what}"))
    }
}

struct Cuda {
    _lib: Library,
    init: unsafe extern "C" fn(c_uint) -> Curesult,
    device_get: unsafe extern "C" fn(*mut Cudevice, c_int) -> Curesult,
    primary_ctx_retain: unsafe extern "C" fn(*mut Cucontext, Cudevice) -> Curesult,
    ctx_set_current: unsafe extern "C" fn(Cucontext) -> Curesult,
    library_load_data: unsafe extern "C" fn(
        *mut Culibrary, *const c_void, *mut c_void, *mut *mut c_void, c_uint,
        *mut c_void, *mut *mut c_void, c_uint,
    ) -> Curesult,
    library_get_kernel: unsafe extern "C" fn(*mut Cukernel, Culibrary, *const c_char) -> Curesult,
    memset_d32: unsafe extern "C" fn(Cudeviceptr, c_uint, usize, Custream) -> Curesult,
    mem_alloc: unsafe extern "C" fn(*mut Cudeviceptr, usize) -> Curesult,
    mem_free: unsafe extern "C" fn(Cudeviceptr) -> Curesult,
    memcpy_h2d: unsafe extern "C" fn(Cudeviceptr, *const c_void, usize) -> Curesult,
    memcpy_d2h: unsafe extern "C" fn(*mut c_void, Cudeviceptr, usize) -> Curesult,
    launch_kernel_ex: unsafe extern "C" fn(
        *const CuLaunchConfig, Cufunction, *mut *mut c_void, *mut *mut c_void,
    ) -> Curesult,
    ctx_synchronize: unsafe extern "C" fn() -> Curesult,
}

impl Cuda {
    fn open() -> Result<Self> {
        let lib = unsafe {
            Library::new("/usr/lib/aarch64-linux-gnu/libcuda.so.1")
                .or_else(|_| Library::new("libcuda.so.1"))
                .or_else(|_| Library::new("libcuda.so"))
        }
        .context("dlopen libcuda.so (need the CUDA driver on the loader path)")?;
        unsafe {
            macro_rules! sym {
                ($n:literal, $t:ty) => {{
                    *lib.get::<$t>($n.as_bytes()).with_context(|| format!("dlsym {}", $n))?
                }};
            }
            let init = sym!("cuInit", unsafe extern "C" fn(c_uint) -> Curesult);
            let device_get = sym!("cuDeviceGet", unsafe extern "C" fn(*mut Cudevice, c_int) -> Curesult);
            let primary_ctx_retain = sym!(
                "cuDevicePrimaryCtxRetain", unsafe extern "C" fn(*mut Cucontext, Cudevice) -> Curesult
            );
            let ctx_set_current = sym!("cuCtxSetCurrent", unsafe extern "C" fn(Cucontext) -> Curesult);
            let library_load_data = sym!(
                "cuLibraryLoadData",
                unsafe extern "C" fn(
                    *mut Culibrary, *const c_void, *mut c_void, *mut *mut c_void, c_uint,
                    *mut c_void, *mut *mut c_void, c_uint,
                ) -> Curesult
            );
            let library_get_kernel = sym!(
                "cuLibraryGetKernel",
                unsafe extern "C" fn(*mut Cukernel, Culibrary, *const c_char) -> Curesult
            );
            let memset_d32 = sym!(
                "cuMemsetD32Async",
                unsafe extern "C" fn(Cudeviceptr, c_uint, usize, Custream) -> Curesult
            );
            let mem_alloc = sym!("cuMemAlloc_v2", unsafe extern "C" fn(*mut Cudeviceptr, usize) -> Curesult);
            let mem_free = sym!("cuMemFree_v2", unsafe extern "C" fn(Cudeviceptr) -> Curesult);
            let memcpy_h2d = sym!("cuMemcpyHtoD_v2", unsafe extern "C" fn(Cudeviceptr, *const c_void, usize) -> Curesult);
            let memcpy_d2h = sym!("cuMemcpyDtoH_v2", unsafe extern "C" fn(*mut c_void, Cudeviceptr, usize) -> Curesult);
            let launch_kernel_ex = sym!(
                "cuLaunchKernelEx",
                unsafe extern "C" fn(
                    *const CuLaunchConfig, Cufunction, *mut *mut c_void, *mut *mut c_void,
                ) -> Curesult
            );
            let ctx_synchronize = sym!("cuCtxSynchronize", unsafe extern "C" fn() -> Curesult);
            Ok(Cuda {
                _lib: lib, init, device_get, primary_ctx_retain, ctx_set_current,
                library_load_data, library_get_kernel, memset_d32, mem_alloc, mem_free,
                memcpy_h2d, memcpy_d2h, launch_kernel_ex, ctx_synchronize,
            })
        }
    }
}

// ---------------- public types (unchanged API) ----------------

#[derive(Clone)]
pub struct VadParams {
    pub threshold: f32,
    pub min_speech_duration_ms: u32,
    pub max_speech_duration_s: f32,
    pub min_silence_duration_ms: u32,
    pub speech_pad_ms: u32,
    pub min_silence_at_max_speech: u32,
    pub use_max_poss_sil_at_max_speech: bool,
}

impl Default for VadParams {
    fn default() -> Self {
        Self {
            threshold: 0.5,
            min_speech_duration_ms: 250,
            max_speech_duration_s: 28.0,
            min_silence_duration_ms: 300,
            speech_pad_ms: 30,
            min_silence_at_max_speech: 98,
            use_max_poss_sil_at_max_speech: true,
        }
    }
}

pub struct Speech { pub start: usize, pub end: usize }

// ---------------- device-buffer slot sizes (f32 elems) ----------------

fn slot_nelems(s: Slot) -> usize {
    use Slot::*;
    match s {
        Xpad => XPAD_LEN,
        Spec => 129 * 4,
        E0 => 128 * 4,
        E1 => 64 * 2,
        E2 => 64 * 1,
        Feat => 128,
        Z => 512,
        Prob => 1,
        H | C | H2 | C2 => 128,
        // weights: sized from their embedded blob at load
        Basis | Ew0 | Ew1 | Ew2 | Ew3 | Eb0 | Eb1 | Eb2 | Eb3
        | Wl | Rl | Lb | Fcw | Fcb => 0,
    }
}

fn slot_index(s: Slot) -> usize { s as u8 as usize }

// ---------------- the model ----------------

pub struct VadModel {
    cuda: Cuda,
    ctx: Cucontext,
    kernels: Vec<(Cufunction, &'static KSpec)>,
    ptr: Vec<Cudeviceptr>, // device ptr per Slot (index = slot_index)
    context: Vec<f32>,     // the 64-sample rolling context (host)
    _libs: Vec<Culibrary>, // keep loaded libraries alive
}

// VadModel is moved across threads by spawn_blocking; the handles are plain
// integers/opaque and the primary context is set current on the worker thread
// before each `speech_timestamps`.
unsafe impl Send for VadModel {}

impl VadModel {
    /// Load the embedded tilelang VAD kernels. No model path or TRT cache — the
    /// cubins and weights are compiled in. Requires `libcuda.so` on the host.
    pub fn load() -> Result<Self> {
        let cuda = Cuda::open()?;
        let mut ctx: Cucontext = std::ptr::null_mut();
        unsafe {
            cuerr((cuda.init)(0), "cuInit")?;
            let mut dev: Cudevice = 0;
            cuerr((cuda.device_get)(&mut dev, 0), "cuDeviceGet")?;
            cuerr((cuda.primary_ctx_retain)(&mut ctx, dev), "cuDevicePrimaryCtxRetain")?;
            cuerr((cuda.ctx_set_current)(ctx), "cuCtxSetCurrent")?;
        }

        let n_slots = KERNELS.iter().flat_map(|k| k.slots.iter()).chain(WEIGHTS.iter().map(|(s, _)| s))
            .copied().map(slot_index).max().map(|m| m + 1).unwrap_or(0).max(slot_index(Slot::C2) + 1);
        let ptr = vec![0u64; n_slots];
        let mut libs = Vec::new();

        // load the 7 cubins and resolve each kernel
        let mut kernels = Vec::new();
        for spec in KERNELS {
            let mut lib: Culibrary = std::ptr::null_mut();
            unsafe {
                cuerr(
                    (cuda.library_load_data)(
                        &mut lib, spec.cubin.as_ptr() as *const c_void,
                        std::ptr::null_mut(), std::ptr::null_mut(), 0,
                        std::ptr::null_mut(), std::ptr::null_mut(), 0,
                    ),
                    "cuLibraryLoadData",
                )?;
            }
            libs.push(lib);
            let name = std::ffi::CString::new(spec.name)?;
            let mut k: Cukernel = std::ptr::null_mut();
            unsafe {
                cuerr((cuda.library_get_kernel)(&mut k, lib, name.as_ptr()), "cuLibraryGetKernel")?;
            }
            kernels.push((k as Cufunction, spec));
        }

        let mut m = VadModel { cuda, ctx, kernels, ptr, context: vec![0.0; CONTEXT], _libs: libs };

        // allocate + upload the 14 resident weight buffers
        for (slot, bytes) in WEIGHTS {
            let dp = m.alloc_upload(bytes)?;
            m.ptr[slot_index(*slot)] = dp;
        }
        // allocate scratch + state slots (zeroed)
        for s in [Slot::Xpad, Slot::Spec, Slot::E0, Slot::E1, Slot::E2, Slot::Feat,
                  Slot::Z, Slot::Prob, Slot::H, Slot::C, Slot::H2, Slot::C2]
        {
            let n = slot_nelems(s);
            let mut dp: Cudeviceptr = 0;
            unsafe {
                cuerr((m.cuda.mem_alloc)(&mut dp, n * 4), "cuMemAlloc scratch")?;
                cuerr((m.cuda.memset_d32)(dp, 0, n, std::ptr::null_mut()), "cuMemsetD32")?;
            }
            m.ptr[slot_index(s)] = dp;
        }
        Ok(m)
    }

    fn alloc_upload(&self, bytes: &[u8]) -> Result<Cudeviceptr> {
        let mut dp: Cudeviceptr = 0;
        unsafe {
            cuerr((self.cuda.mem_alloc)(&mut dp, bytes.len()), "cuMemAlloc weight")?;
            cuerr((self.cuda.memcpy_h2d)(dp, bytes.as_ptr() as *const c_void, bytes.len()), "cuMemcpyHtoD weight")?;
        }
        Ok(dp)
    }

    pub fn reset(&mut self) {
        unsafe {
            cuerr((self.cuda.ctx_set_current)(self.ctx), "cuCtxSetCurrent").ok();
            for &s in &[Slot::H, Slot::C, Slot::H2, Slot::C2] {
                let n = slot_nelems(s);
                cuerr((self.cuda.memset_d32)(self.ptr[slot_index(s)], 0, n, std::ptr::null_mut()), "cuMemsetD32").ok();
            }
        }
        self.context.iter_mut().for_each(|x| *x = 0.0);
    }

    /// Build kernelParams (void**) for `spec` from the current slot ptr table.
    /// Each arg is a device pointer (8 B). Slots referencing H/C/H2/C2 see the
    /// ping-ponged ptrs, so the state swap is just ptr[H]<->ptr[H2], ptr[C]<->ptr[C2].
    unsafe fn launch(&self, spec: &KSpec, func: Cufunction) -> Result<()> {
        let n = spec.slots.len();
        let mut slot_bytes: Vec<[u8; 8]> = Vec::with_capacity(n);
        for &s in spec.slots {
            slot_bytes.push(self.ptr[slot_index(s)].to_le_bytes());
        }
        let mut kparams: Vec<*mut c_void> = slot_bytes.iter_mut().map(|b| b.as_mut_ptr() as *mut c_void).collect();
        let cfg = CuLaunchConfig {
            grid_dim_x: spec.grid[0], grid_dim_y: spec.grid[1], grid_dim_z: spec.grid[2],
            block_dim_x: spec.block[0], block_dim_y: spec.block[1], block_dim_z: spec.block[2],
            shared_mem_bytes: spec.shmem,
            h_stream: std::ptr::null_mut(), attrs: std::ptr::null_mut(), num_attrs: 0,
        };
        cuerr(
            (self.cuda.launch_kernel_ex)(&cfg, func, kparams.as_mut_ptr(), std::ptr::null_mut()),
            "cuLaunchKernelEx",
        )
    }

    /// Run the model on one 512-sample window (zero-padded if short). Mirrors
    /// the reference `OnnxWrapper.__call__`.
    fn forward(&mut self, window: &[f32]) -> Result<f32> {
        // input = context[64] ++ window[512] -> reflect-pad right 64 -> xpad[640]
        let mut xpad = [0f32; XPAD_LEN];
        xpad[..CONTEXT].copy_from_slice(&self.context);
        xpad[CONTEXT..INPUT_LEN].copy_from_slice(&window[..WINDOW]);
        for i in INPUT_LEN..XPAD_LEN {
            // np.pad right-reflect: xpad[i] = xfull[2*N - i - 2], N = INPUT_LEN
            xpad[i] = xpad[2 * INPUT_LEN - i - 2];
        }

        unsafe {
            cuerr((self.cuda.ctx_set_current)(self.ctx), "cuCtxSetCurrent")?;
            cuerr(
                (self.cuda.memcpy_h2d)(
                    self.ptr[slot_index(Slot::Xpad)],
                    xpad.as_ptr() as *const c_void,
                    XPAD_LEN * 4,
                ),
                "cuMemcpyHtoD xpad",
            )?;
            for &(func, spec) in &self.kernels {
                self.launch(spec, func)?;
            }
            // ping-pong state: Kgate wrote h_out/c_out (H2/C2); swap so next call reads them.
            let (h, h2) = (slot_index(Slot::H), slot_index(Slot::H2));
            let (c, c2) = (slot_index(Slot::C), slot_index(Slot::C2));
            self.ptr.swap(h, h2);
            self.ptr.swap(c, c2);

            let mut prob = [0f32; 1];
            cuerr(
                (self.cuda.memcpy_d2h)(
                    prob.as_mut_ptr() as *mut c_void,
                    self.ptr[slot_index(Slot::Prob)],
                    4,
                ),
                "cuMemcpyDtoH prob",
            )?;
            cuerr((self.cuda.ctx_synchronize)(), "cuCtxSynchronize")?;
            // context = last 64 samples of the window
            self.context.copy_from_slice(&window[WINDOW - CONTEXT..]);
            Ok(prob[0])
        }
    }

    /// Faithful port of `get_speech_timestamps`. Returns speech regions as
    /// sample-index half-open intervals [start, end).
    pub fn speech_timestamps(&mut self, audio: &[f32], p: &VadParams) -> Result<Vec<Speech>> {
        let sr = 16000f64;
        let ws = WINDOW;
        let min_speech_samples = sr * p.min_speech_duration_ms as f64 / 1000.0;
        let speech_pad_samples = sr * p.speech_pad_ms as f64 / 1000.0;
        let max_speech_samples = sr * p.max_speech_duration_s as f64 - ws as f64 - 2.0 * speech_pad_samples;
        let min_silence_samples = sr * p.min_silence_duration_ms as f64 / 1000.0;
        let min_silence_at_max = sr * p.min_silence_at_max_speech as f64 / 1000.0;
        let neg_threshold = (p.threshold - 0.15).max(0.01);
        let audio_len = audio.len();

        // --- per-window probabilities (zero-pad the final window) ---
        self.reset();
        let n_windows = audio_len.div_ceil(ws);
        let mut probs: Vec<f32> = Vec::with_capacity(n_windows);
        let mut buf = vec![0f32; WINDOW];
        let mut pos = 0usize;
        while pos < audio_len {
            let take = (audio_len - pos).min(WINDOW);
            buf[..take].copy_from_slice(&audio[pos..pos + take]);
            for b in &mut buf[take..] {
                *b = 0.0;
            }
            probs.push(self.forward(&buf)?);
            pos += ws;
        }

        // --- state machine (port of get_speech_timestamps) ---
        let mut speeches: Vec<Speech> = Vec::new();
        let mut cur_start: Option<usize> = None;
        let mut temp_end = 0usize;
        let mut prev_end = 0usize;
        let mut next_start = 0usize;
        let mut possible_ends: Vec<(usize, f64)> = Vec::new();

        for (i, prob) in probs.iter().enumerate() {
            let cur_sample = ws * i;
            let triggered = cur_start.is_some();

            if *prob >= p.threshold && temp_end != 0 {
                let sil = (cur_sample - temp_end) as f64;
                if sil > min_silence_at_max {
                    possible_ends.push((temp_end, sil));
                }
                temp_end = 0;
                if next_start < prev_end {
                    next_start = cur_sample;
                }
            }

            if *prob >= p.threshold && !triggered {
                cur_start = Some(cur_sample);
                continue;
            }

            if let Some(start) = cur_start {
                if (cur_sample - start) as f64 > max_speech_samples {
                    if p.use_max_poss_sil_at_max_speech && !possible_ends.is_empty() {
                        let (pe, dur) = *possible_ends
                            .iter()
                            .max_by(|a, b| a.1.partial_cmp(&b.1).unwrap())
                            .unwrap();
                        prev_end = pe;
                        speeches.push(Speech { start, end: prev_end });
                        next_start = prev_end + dur as usize;
                        if (next_start as f64) < (prev_end as f64 + cur_sample as f64) {
                            cur_start = Some(next_start);
                        } else {
                            cur_start = None;
                        }
                        prev_end = 0;
                        next_start = 0;
                        temp_end = 0;
                        possible_ends.clear();
                    } else if prev_end != 0 {
                        speeches.push(Speech { start, end: prev_end });
                        if next_start < prev_end {
                            cur_start = None;
                        } else {
                            cur_start = Some(next_start);
                        }
                        prev_end = 0;
                        next_start = 0;
                        temp_end = 0;
                        possible_ends.clear();
                    } else {
                        speeches.push(Speech { start, end: cur_sample });
                        prev_end = 0;
                        next_start = 0;
                        temp_end = 0;
                        cur_start = None;
                        possible_ends.clear();
                        continue;
                    }
                }
            }

            let triggered = cur_start.is_some();
            if *prob < neg_threshold && triggered {
                if temp_end == 0 {
                    temp_end = cur_sample;
                }
                let sil_now = (cur_sample - temp_end) as f64;
                if !p.use_max_poss_sil_at_max_speech && sil_now > min_silence_at_max {
                    prev_end = temp_end;
                }
                if sil_now < min_silence_samples {
                    continue;
                }
                let start = cur_start.take().unwrap();
                let end = temp_end;
                if (end - start) as f64 > min_speech_samples {
                    speeches.push(Speech { start, end });
                }
                prev_end = 0;
                next_start = 0;
                temp_end = 0;
                cur_start = None;
                possible_ends.clear();
                continue;
            }
        }

        if let Some(start) = cur_start {
            if (audio_len - start) as f64 > min_speech_samples {
                speeches.push(Speech { start, end: audio_len });
            }
        }

        let sp_pad = speech_pad_samples as i64;
        for i in 0..speeches.len() {
            if i == 0 {
                speeches[i].start = (speeches[i].start as i64 - sp_pad).max(0) as usize;
            }
            if i != speeches.len() - 1 {
                let silence_dur = speeches[i + 1].start as i64 - speeches[i].end as i64;
                if (silence_dur as f64) < 2.0 * speech_pad_samples {
                    let half = ((silence_dur as f64) / 2.0).floor() as usize;
                    speeches[i].end += half;
                    speeches[i + 1].start = (speeches[i + 1].start as i64 - half as i64).max(0) as usize;
                } else {
                    speeches[i].end = (speeches[i].end + speech_pad_samples as usize).min(audio_len);
                    speeches[i + 1].start = (speeches[i + 1].start as i64 - sp_pad).max(0) as usize;
                }
            } else {
                speeches[i].end = (speeches[i].end + speech_pad_samples as usize).min(audio_len);
            }
        }

        Ok(speeches)
    }
}

impl Drop for VadModel {
    fn drop(&mut self) {
        unsafe {
            for &dp in &self.ptr {
                if dp != 0 {
                    (self.cuda.mem_free)(dp);
                }
            }
        }
    }
}
