// AUTO-GENERATED by scripts/build_vad_kernels.py — do not edit.
// 7 tilelang VAD kernels (cubins) + 14 weight blobs, with per-kernel
// launch specs whose `slots` follow the cubin's actual arg order.

#[repr(u8)] #[derive(Clone, Copy, PartialEq, Eq)]
pub enum Slot {
    Xpad, Basis, Spec, E0, E1, E2, Feat, Z, Prob,
    H, C, H2, C2,
    Ew0, Ew1, Ew2, Ew3, Eb0, Eb1, Eb2, Eb3,
    Wl, Rl, Lb, Fcw, Fcb,
}

pub struct KSpec {
    pub cubin: &'static [u8],
    pub name: &'static str,
    pub grid: [u32; 3],
    pub block: [u32; 3],
    pub shmem: u32,
    pub slots: &'static [Slot],
}

pub const CUBIN_STFT2: &[u8] = include_bytes!("../assets/k_stft2.cubin");
pub const CUBIN_CONV0_2: &[u8] = include_bytes!("../assets/k_conv0_2.cubin");
pub const CUBIN_CONV1_2: &[u8] = include_bytes!("../assets/k_conv1_2.cubin");
pub const CUBIN_CONV2_2: &[u8] = include_bytes!("../assets/k_conv2_2.cubin");
pub const CUBIN_CONV3_2: &[u8] = include_bytes!("../assets/k_conv3_2.cubin");
pub const CUBIN_KZ: &[u8] = include_bytes!("../assets/k_Kz.cubin");
pub const CUBIN_KGATE: &[u8] = include_bytes!("../assets/k_Kgate.cubin");

pub const W_BASIS: &[u8] = include_bytes!("../assets/w_basis.bin");
pub const W_EW0: &[u8] = include_bytes!("../assets/w_ew0.bin");
pub const W_EW1: &[u8] = include_bytes!("../assets/w_ew1.bin");
pub const W_EW2: &[u8] = include_bytes!("../assets/w_ew2.bin");
pub const W_EW3: &[u8] = include_bytes!("../assets/w_ew3.bin");
pub const W_EB0: &[u8] = include_bytes!("../assets/w_eb0.bin");
pub const W_EB1: &[u8] = include_bytes!("../assets/w_eb1.bin");
pub const W_EB2: &[u8] = include_bytes!("../assets/w_eb2.bin");
pub const W_EB3: &[u8] = include_bytes!("../assets/w_eb3.bin");
pub const W_WL: &[u8] = include_bytes!("../assets/w_W.bin");
pub const W_RL: &[u8] = include_bytes!("../assets/w_R.bin");
pub const W_LB: &[u8] = include_bytes!("../assets/w_lb.bin");
pub const W_FCW: &[u8] = include_bytes!("../assets/w_fcw.bin");
pub const W_FCB: &[u8] = include_bytes!("../assets/w_fcb.bin");

pub const WEIGHTS: &[(Slot, &[u8])] = &[
    (Slot::Basis, W_BASIS),
    (Slot::Ew0, W_EW0),
    (Slot::Ew1, W_EW1),
    (Slot::Ew2, W_EW2),
    (Slot::Ew3, W_EW3),
    (Slot::Eb0, W_EB0),
    (Slot::Eb1, W_EB1),
    (Slot::Eb2, W_EB2),
    (Slot::Eb3, W_EB3),
    (Slot::Wl, W_WL),
    (Slot::Rl, W_RL),
    (Slot::Lb, W_LB),
    (Slot::Fcw, W_FCW),
    (Slot::Fcb, W_FCB),
];

pub const KERNELS: &[KSpec] = &[
    KSpec {
        cubin: CUBIN_STFT2, name: "stft2_kernel",
        grid: [9, 1, 1], block: [128, 1, 1],
        shmem: 36864, slots: &[Slot::Basis, Slot::Spec, Slot::Xpad],
    },
    KSpec {
        cubin: CUBIN_CONV0_2, name: "conv_kernel",
        grid: [8, 1, 1], block: [128, 1, 1],
        shmem: 27872, slots: &[Slot::Eb0, Slot::Ew0, Slot::Spec, Slot::E0],
    },
    KSpec {
        cubin: CUBIN_CONV1_2, name: "conv_kernel",
        grid: [4, 1, 1], block: [128, 1, 1],
        shmem: 27648, slots: &[Slot::Eb1, Slot::Ew1, Slot::E0, Slot::E1],
    },
    KSpec {
        cubin: CUBIN_CONV2_2, name: "conv_kernel",
        grid: [4, 1, 1], block: [128, 1, 1],
        shmem: 13312, slots: &[Slot::Eb2, Slot::Ew2, Slot::E1, Slot::E2],
    },
    KSpec {
        cubin: CUBIN_CONV3_2, name: "conv_kernel",
        grid: [8, 1, 1], block: [128, 1, 1],
        shmem: 13056, slots: &[Slot::Eb3, Slot::Ew3, Slot::E2, Slot::Feat],
    },
    KSpec {
        cubin: CUBIN_KZ, name: "Kz_kernel",
        grid: [32, 1, 1], block: [128, 1, 1],
        shmem: 17408, slots: &[Slot::Rl, Slot::Wl, Slot::Lb, Slot::Feat, Slot::H, Slot::Z],
    },
    KSpec {
        cubin: CUBIN_KGATE, name: "Kgate_kernel",
        grid: [1, 1, 1], block: [128, 1, 1],
        shmem: 1024, slots: &[Slot::C, Slot::C2, Slot::Fcb, Slot::Fcw, Slot::H2, Slot::Prob, Slot::Z],
    },
];
