// AUTO-GENERATED by scripts/build_vad_kernels.py — do not edit.
// 1 fused tilelang VAD kernel (cooperative) + 14 weight blobs. The KSpec's
// `slots` follow the cubin's actual arg order (reorder-proof).

#[repr(u8)] #[derive(Clone, Copy, PartialEq, Eq)]
pub enum Slot {
    Xpad, Basis,
    Ew0, Ew1, Ew2, Ew3, Eb0, Eb1, Eb2, Eb3,
    Wl, Rl, Lb, Fcw, Fcb,
    SpecG, E0G, E1G, E2G, FeatG, ZG,
    H, C, Prob,
}

pub struct KSpec {
    pub cubin: &'static [u8],
    pub name: &'static str,
    pub grid: [u32; 3],
    pub block: [u32; 3],
    pub shmem: u32,
    pub cooperative: bool,
    pub slots: &'static [Slot],
}

pub const CUBIN_VAD_STAGED: &[u8] = include_bytes!("../assets/k_vad_staged.cubin");

pub const W_BASIS: &[u8] = include_bytes!("../assets/w_basis.bin");
pub const W_EW0: &[u8] = include_bytes!("../assets/w_ew0.bin");
pub const W_EW1: &[u8] = include_bytes!("../assets/w_ew1.bin");
pub const W_EW2: &[u8] = include_bytes!("../assets/w_ew2.bin");
pub const W_EW3: &[u8] = include_bytes!("../assets/w_ew3.bin");
pub const W_EB0: &[u8] = include_bytes!("../assets/w_eb0.bin");
pub const W_EB1: &[u8] = include_bytes!("../assets/w_eb1.bin");
pub const W_EB2: &[u8] = include_bytes!("../assets/w_eb2.bin");
pub const W_EB3: &[u8] = include_bytes!("../assets/w_eb3.bin");
pub const W_WL: &[u8] = include_bytes!("../assets/w_W.bin");
pub const W_RL: &[u8] = include_bytes!("../assets/w_R.bin");
pub const W_LB: &[u8] = include_bytes!("../assets/w_lb.bin");
pub const W_FCW: &[u8] = include_bytes!("../assets/w_fcw.bin");
pub const W_FCB: &[u8] = include_bytes!("../assets/w_fcb.bin");

pub const WEIGHTS: &[(Slot, &[u8])] = &[
    (Slot::Basis, W_BASIS),
    (Slot::Ew0, W_EW0),
    (Slot::Ew1, W_EW1),
    (Slot::Ew2, W_EW2),
    (Slot::Ew3, W_EW3),
    (Slot::Eb0, W_EB0),
    (Slot::Eb1, W_EB1),
    (Slot::Eb2, W_EB2),
    (Slot::Eb3, W_EB3),
    (Slot::Wl, W_WL),
    (Slot::Rl, W_RL),
    (Slot::Lb, W_LB),
    (Slot::Fcw, W_FCW),
    (Slot::Fcb, W_FCB),
];

pub const KERNELS: &[KSpec] = &[
    KSpec {
        cubin: CUBIN_VAD_STAGED, name: "vad_staged_kernel",
        grid: [32, 1, 1], block: [128, 1, 1],
        shmem: 17408, cooperative: true, slots: &[Slot::Lb, Slot::Rl, Slot::Wl, Slot::Basis, Slot::C, Slot::E0G, Slot::E1G, Slot::E2G, Slot::Eb0, Slot::Eb1, Slot::Eb2, Slot::Eb3, Slot::Ew0, Slot::Ew1, Slot::Ew2, Slot::Ew3, Slot::Fcb, Slot::Fcw, Slot::FeatG, Slot::H, Slot::Prob, Slot::SpecG, Slot::Xpad, Slot::ZG],
    },
];
